export const NATIONALITIES_ABBR = {
  AU: "AU",
  BR: "BR",
  CA: "CA",
  CH: "CH",
  DE: "DE",
  DK: "DK",
  ES: "ES",
  FI: "FI",
  FR: "FR",
  GB: "GB",
  IE: "IE",
  IR: "IR",
  NO: "NO",
  NL: "NL",
  NZ: "NZ",
  TR: "TR",
  US: "US",
};

export const NATIONALITIES_NAMES = {
  [NATIONALITIES_ABBR.AU]: "Australian",
  [NATIONALITIES_ABBR.BR]: "Brazilian",
  [NATIONALITIES_ABBR.CA]: "Canadian",
  [NATIONALITIES_ABBR.CH]: "Swiss",
  [NATIONALITIES_ABBR.DE]: "German",
  [NATIONALITIES_ABBR.DK]: "Danish",
  [NATIONALITIES_ABBR.ES]: "Spanish",
  [NATIONALITIES_ABBR.FI]: "Finnish",
  [NATIONALITIES_ABBR.FR]: "French",
  [NATIONALITIES_ABBR.GB]: "British",
  [NATIONALITIES_ABBR.IE]: "Irish",
  [NATIONALITIES_ABBR.IR]: "Iranian",
  [NATIONALITIES_ABBR.NO]: "Norwegian",
  [NATIONALITIES_ABBR.NL]: "Dutch",
  [NATIONALITIES_ABBR.NZ]: "New Zealander",
  [NATIONALITIES_ABBR.TR]: "Turkish",
  [NATIONALITIES_ABBR.US]: "American",
};
